### ISSUE TITLE
New proposal about `exec` and `switches`

### ISSUE THREAD

**Issue by Berrysoft** [Uni-Gal/Ayaka#45]
## 解耦合 `exec`

将 `exec` 做成 line plugin。允许一个插件调用另一个插件（ #14 ）。

## 简化 `switches`

不再允许每个选项后面给出代码，这样能够解决 #24 。

每个选项默认绑定其顺序对应的数字名称变量，默认值为 `true`；被选择的选项将进入 `$?`。例如：

``` yaml
- exec: $1 = false
- switches:
  - Switch 1
  - Switch 2
  - Switch 3
- exec: $n = $?
```

在上述示例中，第一、三个选项可用而第二个选项不可用；`$n` 的值可能取0或2。

有关默认值的考虑：
* 如果设定成 `false` 可用而 `true` 不可用，太扭曲了。
* 但是一个 `bool` 值默认是 `true` 也很扭曲。
* 因此决定，如果这个变量是 `null` 的时候为 `true`，其它情况与正常变量保持相同。这并不构成 Ayaka Script 的例外规则，而是 `switches` 的特殊规则。
